[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim') && has('python3')"
on_event = 'InsertCharPre'
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option("enable_smart_case", 1)
    call deoplete#custom#option("auto_complete_delay", 0)

    inoremap <expr><C-l> deoplete#complete_common_string()
    inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
depends = 'neosnippet-snippets'
hook_add = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'arakashic/chromatica.nvim'
if = "has('nvim')"
on_ft = 'cpp'
hook_add = '''
    let g:chromatica#libclang_path = '/usr/local/opt/llvm/lib'
    let g:chromatica#enable_at_startup = 1
    let g:chromatica#responsive_mode = 1
'''

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
depends = "deoplete.nvim"
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'w0rp/ale'
if = 'has("nvim")'
on_ft = ['c', 'cpp', 'python', 'ruby']
hook_add = '''
    let g:ale_linters = {
        \ 'c': ['gcc', 'clang'],
        \ 'cpp': ['g++', 'clang++'],
        \ 'python': ['flake8', 'python'],
        \ 'ruby': ['ruby'],
    \ }
    let g:ale_sign_column_always = 1
    let g:ale_lint_on_text_changed = "normal"
    let g:ale_lint_on_insert_leave = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
